  version: '3.7'
  services:
    roofui:
      image: root
      ports:
        - "8080:80"   

    mongo:
      image: mongo
      ports:
        - "27017:27017"        

    roofservice:
      image: roof-service

      depends_on:
        - mongo
      ports:
        - "8060:8060"   
